server:
  port: 7901

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.nh.sc.entity   # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: provideruser #应用名称，别名
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包  mysql8.0以后 驱动包路径改为com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc02?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false              # 数据库名称
    username: root
    password: 1thisismypwd
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:10000/eureka,http://eureka02:10001/eureka  #同时注册到01和02
  instance:
    prefer-ip-address: true #info链接以ip的形式显示
    instance-id: provider02 #status列表中显示的名称
info:
  app.name: com.nh.scDemo
  company.name: nohatC
  build.artifactId: $project.artifactId$
  build.version: $project.version$
