server:
  port: 7901

spring:
  application:
    name: provider-user02 #应用名称，别名

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:10000/eureka,http://eureka02:10001/eureka  #同时注册到01和02
  instance:
    prefer-ip-address: true #info链接以ip的形式显示
    instance-id: provider02 #status列表中显示的名称
info:
  app.name: com.nh.scDemo
  company.name: nohatC
  build.artifactId: $project.artifactId$
  build.version: $project.version$
