server:
  port: 10001
  #context-path: /Eureka02
eureka:
  client:
    register-with-eureka: false #表示不向注册中心注册自己 自己已经是注册中心
    fetch-registry: false #表示自己就是注册中心，不需要去检索服务
    service-url:
      defaultZone: http://eureka01:10000/eureka
  instance:
    hostname: eureka02
security:
  basic:
    enabled: false



